#!/usr/bin/env node
var getFile = require('./index.js')
var fs = require('fs');
var file = process.argv[2]
fs.readFile(`${file}`, 'utf8', function(err, data) {
    if (err) throw err;
    var input = data;
    console.log(getFile(input));
});