#!/usr/bin/env node
const getFile = require('./index.js');
const fs = require('fs');
const minimist = require('minimist');

const alias = {
	output: 'o'
}
const argv = minimist(process.argv.slice(2), alias);

const file = getFile(fs.readFileSync(argv._[0], { encoding: 'utf8' }));
fs.writeFileSync(argv.o || `${argv._[0]}.css`, file, { encoding: 'utf8'})